### ISSUE TITLE
[doc] try-with-resources closes span before calling catch / finally blocks

### ISSUE THREAD

**Issue by wsargent** [honeycombio/beeline-java#10]
In https://docs.honeycomb.io/getting-data-in/java/beeline/#installation-with-any-java-application there is an example that uses a try-with-resources block:

```java
public static class DatabaseService {
    public void queryDb(String id) {
        try (Span childSpan = beeline.startChildSpan("customer-db-query")) {
            String data = getCustomerDataById(id);
            childSpan.addField("customer-data", data);
        }

    }

    public String getCustomerDataById(String id) {
        return "customer-0123";
    }
}
```

This is potentially dangerous, as a try-with-resources combined with a catch block will close the span before any catch or finally blocks get a chance to execute.

From https://github.com/Nike-Inc/wingtips#try_with_resources_warning

> The try-with-resources feature to auto-close spans as described above can sound very tempting due to its convenience, but it comes with an important and easy-to-miss tradeoff: **the span will be closed before any catch or finally blocks get a chance to execute**. So if you need to catch any exceptions and log information about them (for example), then you do not want to use the try-with-resources shortcut because that logging will not be tagged with the span info of the span it logically falls under, and if you try to retrieve Tracer.getInstance().getCurrentSpan() then you'll either get the parent span if one exists or null if there was no parent span. This can be confusing and seem counter-intuitive, but it's the way try-with-resources works and is the price we pay for (ab)using it for convenience in a use case it wasn't originally intended for (Spans are not "resources" in the traditional sense).

**Comment by vreynolds** [comment]
Thanks for raising @wsargent ! Example updated.
