### ISSUE TITLE
Spring Boot Starter ignores proxy settings

### ISSUE THREAD

**Issue by veryhappythings** [honeycombio/beeline-java#129]
The Spring Boot starter includes a default Transport bean https://github.com/honeycombio/beeline-java/blob/main/beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java#L147 which, as you won't have a transport set up by the time you hit this, creates you a transport at boot time (to create the default honeycomb client here https://github.com/honeycombio/beeline-java/blob/main/beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java#L91). This default transport ignores your proxy options, and then, as the honeycomb client has a transport handed in, it also ignores your transport options. Therefore, the `proxyHostname`, `proxyUsername`, and `proxyPassword` options are effectively ignored completely.

This means that this section of code is ignored: https://github.com/honeycombio/beeline-java/blob/main/beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java#L114-L127 - it sets up the proxy on the `HoneyClientBuilder`, but when we come to build the `HoneyClient`, we ignore these options in favour of our existing `Transport` https://github.com/honeycombio/libhoney-java/blob/main/libhoney/src/main/java/io/honeycomb/libhoney/builders/HoneyClientBuilder.java#L64-L69

I've worked around this by building my own `defaultBeelineTransport` bean, which lifts the proxy config from https://github.com/honeycombio/libhoney-java/blob/main/libhoney/src/main/java/io/honeycomb/libhoney/builders/HoneyClientBuilder.java to process these options correctly. It's not very elegant - it feels like we should be able to leave this to the client builder, using the options instead of the transport, but that feels like the kind of API change that breaks things in unexpected ways.

What do you reckon, folks? What's the best way to fix this?

**Comment by JamieDanielson** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
