### ISSUE TITLE
Spring Boot 2.6.x application fails to start because of circular dependencies in BeelineAutoconfig

### ISSUE THREAD

**Issue by kardashov** [honeycombio/beeline-java#180]
After Spring Boot 2.5.x -> 2.6.2 upgrade application fails to start with following error message:

***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
┌──->──┐
|  io.honeycomb.beeline.spring.autoconfig.BeelineAutoconfig (field private io.honeycomb.beeline.spring.beans.BeelineHandlerInterceptor io.honeycomb.beeline.spring.autoconfig.BeelineAutoconfig.beelineHandlerInterceptor)
└──<-──┘

Action:
Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Versions**

- Java: 11
- Beeline: beeline-spring-boot-starter:1.5.0 and 1.7.0

**Additional Context**
In Spring Boot 2.6  Circular References are now Prohibited by Default
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#circular-references-prohibited-by-default
We applied spring.main.allow-circular-references=true temporarily, but BeelineAutoconfig  is the only component which doesn't behave well with default settings in our system.

**Comment by seadub** [comment]
+1. The workaround works but is not acceptable long-term.

**Comment by giorgimode** [comment]
Facing the same issue. `spring.main.allow-circular-references=true` is a no-go for me

**Comment by giorgimode** [comment]
Issue has been fixed by my PR above

**Comment by vreynolds** [comment]
should be fixed in latest release: https://github.com/honeycombio/beeline-java/releases/tag/v1.7.1
