### ISSUE TITLE
DefaultBeeline#close() is misleading

### ISSUE THREAD

**Issue by tomoNeoworks** [honeycombio/beeline-java#19]
The call to  [Tracer#endTrace()](https://github.com/honeycombio/beeline-java/blob/master/beeline-core/src/main/java/io/honeycomb/beeline/DefaultBeeline.java#L154) will only end the thread-local trace, i.e. the trace local to the thread that happened to call DefaultBeeline#close(). I think a reader may think that this is closing all traces, so may be misled.

If we look at the way the Spring Beeline works, the trace management is done by the BeelineServletFilter because it can open and close the traces on each HTTP thread. It doesn't use a global 'close' method, which appears to be the intent of DefaultBeeline#close().

**Comment by nathanleclaire** [comment]
`DefaultBeeline#endTrace` should do the trick, philosophical / API design questions aside.
