### ISSUE TITLE
How to upgrade beeline-core from 1.x to 2.x for a spring-boot application

### ISSUE THREAD

**Issue by zhoudxnz** [honeycombio/beeline-java#235]
Hello,

I tried to upgrade beeline from 1.x to 2.x for our spring boot application (2.5.7). After bumping the version of beeling-spring-boot-starter to 2.1.0 in build.gradle,  I notice it pulls in beeline-core 1.6.1 instead of 2.1.0. 

`implementation 'io.honeycomb.beeline:beeline-spring-boot-starter:2.1.0'`

https://github.com/honeycombio/beeline-java/blob/6ee618c29d01b6ae077b5f83ec40b0a80f725f9c/beeline-spring-boot-starter/pom.xml#L19

Is this intentional? What is the correct way to upgrade a spring boot application to beeline-core 2.1.0? 

Thank you!

**Comment by MikeGoldsmith** [comment]
Hi @zhoudxnz - thanks for raising the issue.

There isn't specific reason why the spring boot package doesn't use the latest beeline. There are a few outstanding dependency updates that I'll work through and will update this package to latest beeline too.

**Comment by MikeGoldsmith** [comment]
Sorry for delay, release PR is now up - I expect it to merge & release today.
- #249

**Comment by MikeGoldsmith** [comment]
@zhoudxnz v2.1.1 has been released, which includes updating both the Spring Boot & Sleuth packages to use the latest beeline :+1
