### ISSUE TITLE
Spring Sleuth Integration

### ISSUE THREAD

**Issue by johnmphillips** [honeycombio/beeline-java#3]
We have some applications that have spring-sleuth integration for log correlation. We'd love to use honeycomb to instrument them also, but wouldn't want two sets of trace/spanID's floating around. Would it be possible to make the beeline sleuth-aware?

**Comment by asdvalenzuela** [comment]
Hi John! I'd love to chat with you a bit more about this request, and will follow up via Intercom.

**Comment by vreynolds** [comment]
We’re going to close this for now. Feel free to re-open if it’s still relevant.
