### ISSUE TITLE
Beeline does not capture errors consistenly

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/beeline-java#42]
We are using the Spring Boot beeline (`beeline-spring-boot-starter:1.1.0`) and we noticed that some events would not have a status code.

Digging a bit deeper lead us to conclude that requests that throw exceptions do not provide consistent fields:
- if the exception is captured by a `@ControllerAdvice` class we only get `response.status_code` but no `request.error` or `request.error_detail`
- if the exception is not captured we get `response.status_code` but no `request.error` or `request.error_detail`

I made a basic app to demonstrate this. There are two endpoints: `/foo` and `/bar`, which both throw runtime exceptions but only `/foo` is captured by a `@ControllerAdvice` class.
Check out the code here: https://github.com/kvrhdn/beeline-java-controlleradvice

Result:
<img width="1330" alt="Screenshot 2020-05-14 at 02 10 03" src="https://user-images.githubusercontent.com/7748404/81878893-8b660a80-9589-11ea-9409-09066a94c721.png">

I _assume_ this has something to do with the order of the interceptor used by the beeline, it seems likely that `@ControllerAdvice` 'eats' the exception before the beeline can see it.

My questions are:
- Is this a known issue? If so, could we document this because this is really unexpected + it's causing me to miss errors.
- Is there a recommended workaround?

**Comment by robbkidd** [comment]
We’re going to close this for now from inactivity. Feel free to re-open if the issue described here is still relevant.
