### ISSUE TITLE
Non-compiling documentation sample code

### ISSUE THREAD

**Issue by MysterAitch** [honeycombio/beeline-java#48]
Hi,

Is intentional that the sample code does not compile when used as-is? _(linked and quoted below below)_

Specifically note that beeline and client are private static fields within `TracerSpans`, in addition to also creating an instance of `TracerSpans`. 

It is within the "advanced" section, so it might just be that there's something I'm not yet aware of or familiar with as a Honeycomb novice! :+1: 

https://docs.honeycomb.io/getting-data-in/java/beeline/#installation-with-any-java-application-advanced

```java
public static void main(String... args) {
        TracerSpans example = new TracerSpans();
    try {
        HttpRequest request = new HttpRequest();
        startTrace(request);
        example.acceptRequest(request);
    } finally {
        beeline.getTracer().endTrace();
        client.close(); // close to flush events and release its thread pool
    }
}
```

**Comment by JamieDanielson** [comment]
Sorry for the delayed response! Hopefully you were able to get things sorted out - sounds like the missing piece was this block below, which is in docs now but we'll be further updating those docs a bit to help with clarity. We are focusing our efforts now on OpenTelemetry and have a Honeycomb Distribution for Java that you may be interested to try if you haven't already.

```java
public class TracerSpans {
    private static final String WRITE_KEY = "test-write-key";
    private static final String DATASET = "test-dataset";

    private static final HoneyClient client;
    private static final Beeline beeline;

    static {
        client                          = LibHoney.create(LibHoney.options().setDataset(DATASET).setWriteKey(WRITE_KEY).build());
        SpanPostProcessor postProcessor = Tracing.createSpanProcessor(client, Sampling.alwaysSampler());
        SpanBuilderFactory factory      = Tracing.createSpanBuilderFactory(postProcessor, Sampling.alwaysSampler());
        Tracer tracer                   = Tracing.createTracer(factory);
        beeline                         = Tracing.createBeeline(tracer, factory);
    }
}
```
