### ISSUE TITLE
Spring Boot property 'honeycomb.beeline.jdbc.enabled' is not documented

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/beeline-java#55]
Just a small note: the property `honeycomb.beeline.jdbc.enabled` as used here:
https://github.com/honeycombio/beeline-java/blob/main/beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java#L221

Is not mentioned `spring-configuration-metadata.json`
https://github.com/honeycombio/beeline-java/blob/main/beeline-spring-boot-sleuth-starter/src/main/resources/META-INF/spring-configuration-metadata.json

This makes that autocomplete does not work / IntelliJ shows a warning:

<img width="535" alt="Screenshot 2020-07-22 at 18 27 19" src="https://user-images.githubusercontent.com/7748404/88202493-3f9aa600-cc49-11ea-8c63-0faf0c9b1023.png">

**Comment by MikeGoldsmith** [comment]
Ah, thanks for the bug report. We'll get that fixed up ASAP.
