### ISSUE TITLE
Create startSpan API

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#6]
All this boilerplate to create a new span/trace is a bummer - 

```java
Span rootSpan = beeline.getSpanBuilderFactory().createBuilder()
    .setSpanName("get-customer-data")
    .setServiceName("customer-db-traced")
    .setParentContext(context)
    .build();
beeline.getTracer().startTrace(rootSpan);
```

The other Beelines have a way to call `beeline.startSpan`, which will create a trace if one does not exist yet (and otherwise create a new child span), the Java Beeline is more manual today. Create a smoother API to `startTrace` all in one.

**Comment by asdvalenzuela** [comment]
resolved in https://github.com/honeycombio/beeline-java/pull/13
