### ISSUE TITLE
Beeline Sleuth Autoconfig doesn't declare that it needs to be configured before Sleuth

### ISSUE THREAD

**Issue by osi** [honeycombio/beeline-java#67]
in `BeelineSleuthAutoconfig`, it should declare `@AutoConfigureBefore(TraceAutoConfiguration.class)` so that the `Reporter` is available for the trace autoconfig to pick up.

Without this, I'm seeing the Beeline Sleuth config happening after the Trace config, resulting in the reporter not being added to the tracer.

**Comment by MikeGoldsmith** [comment]
Hi @osi - thanks for the bug report. We'll look into it shortly.

**Comment by osi** [comment]
Thanks for merging the fix! Does this automatically kick off a new build to the central repo, or is that a manual process?

**Comment by paulosman** [comment]
> Thanks for merging the fix! Does this automatically kick off a new build to the central repo, or is that a manual process?

Thanks for the PR! That's a manual process for now. We'll aim to cut a release on Monday.
