### ISSUE TITLE
Consider 'close' => 'send'

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-java#8]
What seems to be usually `close` method here is often called `span.Send()` in other beelines

**Comment by toshok** [comment]
`close` is needed for the `AutoCloseable` interface.  Think of it as python's custom context manager stuff.

it could _call_ `send`, certainly.  but they don't have to be mutually exclusive.

**Comment by nathanleclaire** [comment]
Ah, interesting. Good context, thanks.

**Comment by eanakashima** [comment]
@nathanleclaire @toshok ok to close this? Or is there still work to do here?

**Comment by nathanleclaire** [comment]
Isn't urgent imo.

**Comment by nathanleclaire** [comment]
going to just close since it seems `close` is ok, just inconsistent with other beelines
